defaults: &defaults
  google_custom_search_id: ""
  secret_token: "55eae02566fdd7adb439b51e241b9229d5d9dd11a415b2590825b9ba243ea2ca391b1723f386834793cf60967a9262b9216bbb4881cae86dbf9ce5823e3b5d11"
  admin_emails:
    - "admin@codecampo.com"
    - "linhongshimouse@gmail.com"
    - "yijo1001@gmail.com"

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
